# site title
title: Mashiro's Blog

# user name or organization name
user: Mashiro

# issue repository
repository: Mashiro-s-Issue-Blog

# multi-author
authors: MashiroWang

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: f743c6db2523f5dbb5f6cf78f61195484fa63d76

# posts per page
perpage: 10


# advance config

# organization repository (?)
organization: false

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'UPDATED_AT'
