# site title
title: Mashiro's Blog

# user name or organization name
user: MashiroWang

# issue repository
repository: Mashiro-s-Issue-Blog

# multi-author
authors:

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 4#fc55d7c516bffdcbbfb6e28478521dd7bf7944f

# posts per page
perpage: 10


# advance config

# organization repository (?)
organization: false

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'UPDATED_AT'
